snr: 10
multiple_sample: 5
scheduled_sampling_start: 18
iscomplex: 1
channel_type: 'awgn'
batch_size: 64 #64
channel_dim: 32 #256
ckpt_resume: 88
lr_milestones: '160'
max_epoch: 202
seeds: 7
init_learning_rate: 1e-4
save_model_path: './ckpt_AWGN_CE_Stage2/'
RL_training: 0
device: 'cuda:0'
backbone: 'LSTM'
